import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/components/Providers";
import { Toaster } from "react-hot-toast";
// import { getSession } from "next-auth/react";
import { getServerSession } from "next-auth";
import authOptions from "./api/auth/[...nextauth]/options";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // const session=await getSession();
  // console.log("Layout Session =>",session);
  //  console.log("SERVER SESSION",await getServerSession());

  const serverSession = await getServerSession(authOptions);
  console.log("Layout Check of Session =>",serverSession);
  
  return (
    <Providers session={serverSession} >
      <html lang="en">
        <body className={inter.className}>
          {children}
          <Toaster />
        </body>
      </html>
    </Providers>
  );
}
